site_name: Raven
site_author: Crownest
copyright: Crownest
site_dir: docs_build
use_directory_urls: false

pages:
  - Home: index.md
  - Backend:
    - Celery: backend/celery.md
    - Development: backend/development.md
  - Frontend:
    - Development: frontend/development.md
