# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Canceled')], default=0, verbose_name='Status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='departments.Department', verbose_name='Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Registration Request',
                'verbose_name_plural': 'Registration Requests',
            },
        ),
    ]
